<?php

namespace AppBundle\Repository;

/**
 * DiscoMasterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscoMasterRepository extends \Doctrine\ORM\EntityRepository
{
}
