<?php

namespace AppBundle\Repository;

/**
 * DiscotecaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscotecaRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllDiscotecas(){
        return $this->getEntityManager()->createQuery("Select o FROM AppBundle:Discoteca o")->getResult();
    }
}
