<?php

namespace AppBundle\Repository;

/**
 * RangoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RangoRepository extends \Doctrine\ORM\EntityRepository
{
}
