<?php

namespace AppBundle\Repository;

/**
 * RRPPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RRPPRepository extends \Doctrine\ORM\EntityRepository
{
}
